version: '3'

services:

  springboot:
    build: ./be
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod


  nginx:
    build: ./nginx
    container_name: nginx-proxy
    depends_on:
      - springboot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl

